version: "3.8"

services:
  fastapi:
    build: .
    container_name: sci-find-backend
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  # nlp-service:
  #   image: huggingface/transformers-pytorch-cpu:latest
  #   container_name: sci-find-nlp
  #   environment:
  #     - TRANSFORMERS_CACHE=/cache
  #   volumes:
  #     - ./cache:/cache
  #   depends_on:
  #     - elasticsearch
  #   command: ["tail", "-f", "/dev/null"]

volumes:
  esdata:
